// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZhmApi.Data;

#nullable disable

namespace ZhmApi.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20251127091554_UserSeedOnDatabaseUpdate")]
    partial class UserSeedOnDatabaseUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZhmApi.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Regular patient with access to personal medical records.",
                            Name = "Patient"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Medical doctor responsible for patient care.",
                            Name = "General Practitioner"
                        });
                });

            modelBuilder.Entity("ZhmApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GeneralPractitionerId")
                        .HasColumnType("int");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNumberAddition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GeneralPractitionerId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Sampletown",
                            Country = "Country",
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            HouseNumber = "12",
                            LastName = "Doe",
                            PasswordHash = "hashedpassword123",
                            PhoneNumber = "1234567890",
                            PostalCode = "12345",
                            Province = "Province",
                            RoleId = 2,
                            Street = "Main Street",
                            TwoFactorEnabled = false,
                            ZipCode = "12345"
                        },
                        new
                        {
                            Id = 2,
                            City = "Examplecity",
                            Country = "Country",
                            Email = "alice.smith@example.com",
                            FirstName = "Alice",
                            GeneralPractitionerId = 1,
                            HouseNumber = "34",
                            LastName = "Smith",
                            PasswordHash = "hashedpassword456",
                            PhoneNumber = "0987654321",
                            PostalCode = "54321",
                            Province = "Province",
                            RoleId = 1,
                            Street = "Second Street",
                            TwoFactorEnabled = false,
                            ZipCode = "54321"
                        });
                });

            modelBuilder.Entity("ZhmApi.Models.User", b =>
                {
                    b.HasOne("ZhmApi.Models.User", "GeneralPractitioner")
                        .WithMany("Patients")
                        .HasForeignKey("GeneralPractitionerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ZhmApi.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneralPractitioner");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ZhmApi.Models.User", b =>
                {
                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
