/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(protected)': RouteRecordInfo<
      '/(protected)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '/(protected)/'
      | '/(protected)/[...path]'
      | '/(protected)/afspraken/'
      | '/(protected)/afspraken/create'
      | '/(protected)/patient/'
      | '/(protected)/patient/requests'
      | '/(protected)/referrals/'
      | '/(protected)/referrals/new'
      | '/(protected)/specialist/'
      | '/(protected)/specialist/SpecialistAccessRequests'
      | '/(protected)/specialist/SpecialistRequestAccess'
    >,
    '/(protected)/': RouteRecordInfo<
      '/(protected)/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(protected)/[...path]': RouteRecordInfo<
      '/(protected)/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/(protected)/afspraken/': RouteRecordInfo<
      '/(protected)/afspraken/',
      '/afspraken',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(protected)/afspraken/create': RouteRecordInfo<
      '/(protected)/afspraken/create',
      '/afspraken/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(protected)/patient/': RouteRecordInfo<
      '/(protected)/patient/',
      '/patient',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(protected)/patient/requests': RouteRecordInfo<
      '/(protected)/patient/requests',
      '/patient/requests',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(protected)/referrals/': RouteRecordInfo<
      '/(protected)/referrals/',
      '/referrals',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(protected)/referrals/new': RouteRecordInfo<
      '/(protected)/referrals/new',
      '/referrals/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(protected)/specialist/': RouteRecordInfo<
      '/(protected)/specialist/',
      '/specialist',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(protected)/specialist/SpecialistAccessRequests': RouteRecordInfo<
      '/(protected)/specialist/SpecialistAccessRequests',
      '/specialist/SpecialistAccessRequests',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(protected)/specialist/SpecialistRequestAccess': RouteRecordInfo<
      '/(protected)/specialist/SpecialistRequestAccess',
      '/specialist/SpecialistRequestAccess',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth': RouteRecordInfo<
      '/auth',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | '/auth/2fa'
      | '/auth/login'
      | '/auth/registreren'
    >,
    '/auth/2fa': RouteRecordInfo<
      '/auth/2fa',
      '/auth/2fa',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/login': RouteRecordInfo<
      '/auth/login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/registreren': RouteRecordInfo<
      '/auth/registreren',
      '/auth/registreren',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(protected).vue': {
      routes:
        | '/(protected)'
        | '/(protected)/'
        | '/(protected)/[...path]'
        | '/(protected)/afspraken/'
        | '/(protected)/afspraken/create'
        | '/(protected)/patient/'
        | '/(protected)/patient/requests'
        | '/(protected)/referrals/'
        | '/(protected)/referrals/new'
        | '/(protected)/specialist/'
        | '/(protected)/specialist/SpecialistAccessRequests'
        | '/(protected)/specialist/SpecialistRequestAccess'
      views:
        | 'default'
    }
    'src/pages/(protected)/index.vue': {
      routes:
        | '/(protected)/'
      views:
        | never
    }
    'src/pages/(protected)/[...path].vue': {
      routes:
        | '/(protected)/[...path]'
      views:
        | never
    }
    'src/pages/(protected)/afspraken/index.vue': {
      routes:
        | '/(protected)/afspraken/'
      views:
        | never
    }
    'src/pages/(protected)/afspraken/create.vue': {
      routes:
        | '/(protected)/afspraken/create'
      views:
        | never
    }
    'src/pages/(protected)/patient/index.vue': {
      routes:
        | '/(protected)/patient/'
      views:
        | never
    }
    'src/pages/(protected)/patient/requests.vue': {
      routes:
        | '/(protected)/patient/requests'
      views:
        | never
    }
    'src/pages/(protected)/referrals/index.vue': {
      routes:
        | '/(protected)/referrals/'
      views:
        | never
    }
    'src/pages/(protected)/referrals/new.vue': {
      routes:
        | '/(protected)/referrals/new'
      views:
        | never
    }
    'src/pages/(protected)/specialist/index.vue': {
      routes:
        | '/(protected)/specialist/'
      views:
        | never
    }
    'src/pages/(protected)/specialist/SpecialistAccessRequests.vue': {
      routes:
        | '/(protected)/specialist/SpecialistAccessRequests'
      views:
        | never
    }
    'src/pages/(protected)/specialist/SpecialistRequestAccess.vue': {
      routes:
        | '/(protected)/specialist/SpecialistRequestAccess'
      views:
        | never
    }
    'src/pages/auth.vue': {
      routes:
        | '/auth'
        | '/auth/2fa'
        | '/auth/login'
        | '/auth/registreren'
      views:
        | 'default'
    }
    'src/pages/auth/2fa.vue': {
      routes:
        | '/auth/2fa'
      views:
        | never
    }
    'src/pages/auth/login.vue': {
      routes:
        | '/auth/login'
      views:
        | never
    }
    'src/pages/auth/registreren.vue': {
      routes:
        | '/auth/registreren'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
