/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(protected)': RouteRecordInfo<
      '/(protected)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '/(protected)/'
      | '/(protected)/[...path]'
    >,
    '/(protected)/': RouteRecordInfo<
      '/(protected)/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(protected)/[...path]': RouteRecordInfo<
      '/(protected)/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/auth': RouteRecordInfo<
      '/auth',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | '/auth/login'
      | '/auth/registreren'
      | '/auth/verificatie'
    >,
    '/auth/login': RouteRecordInfo<
      '/auth/login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/registreren': RouteRecordInfo<
      '/auth/registreren',
      '/auth/registreren',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/verificatie': RouteRecordInfo<
      '/auth/verificatie',
      '/auth/verificatie',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(protected).vue': {
      routes:
        | '/(protected)'
        | '/(protected)/'
        | '/(protected)/[...path]'
      views:
        | 'default'
    }
    'src/pages/(protected)/index.vue': {
      routes:
        | '/(protected)/'
      views:
        | never
    }
    'src/pages/(protected)/[...path].vue': {
      routes:
        | '/(protected)/[...path]'
      views:
        | never
    }
    'src/pages/auth.vue': {
      routes:
        | '/auth'
        | '/auth/login'
        | '/auth/registreren'
        | '/auth/verificatie'
      views:
        | 'default'
    }
    'src/pages/auth/login.vue': {
      routes:
        | '/auth/login'
      views:
        | never
    }
    'src/pages/auth/registreren.vue': {
      routes:
        | '/auth/registreren'
      views:
        | never
    }
    'src/pages/auth/verificatie.vue': {
      routes:
        | '/auth/verificatie'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
